rvm:
  - 1.9.3
  - 2.1.2
gemfile:
  - gemfiles/Gemfile.rails-3.2
  - gemfiles/Gemfile.rails-4.0
notifications:
  recipients:
    - michal.lomnicki@gmail.com
    - ronen@barzel.org
    - toby@ovod-everett.org
